### ISSUE TITLE
Custom chunks and STL iostream read/write

### ISSUE THREAD

**Issue by skrat** [jessey-git/fx-gltf#59]
Hello, I'm looking to replace tinygltf with something more flexible. Both tinygltf and fx-gltf don't have support for reading from `std::istream` and writing to `std::ostream` which is essential for my application, and I think it's better abstraction and more flexible than filenames, and assuming the client wants to use filesystem to store possibly intermediate data.

Another problem with both libraries is lack of support for custom chunks in the binary input/output. My application works with single .glb file containing all the vertex and image data, and also utilizes JSON `extra` and custom binary chunk for storing app specific data. 

I would like to contribute to this library and I'm wondering if there's a will in the upstream to merge these improvements. Thank you

**Comment by jessey-git** [comment]
Hi Skrat, thanks for the suggestions and the PR.  I think having an iostream interface option sounds reasonable at first glance and I'd be willing to see how that might integrate here.  As for the extra chunks, I will need to think about that a bit.

My time is somewhat limited these days but I'll leave some initial comments from my very brief look through the code in a bit.  It would be best if these were submitted as 2 separate PRs though to keep things separated.

**Comment by jessey-git** [comment]
As a followup for the extra chunks, I spoke a little bit with the folks running glTF and I'll update this comment here as replies come in etc.

Summary:
- Prefer to use custom bufferViews into the main BIN chunk for custom data (all the machinery is already in place as bufferViews let you know how/where to access it)
- In either case, extensions should be used to identify how to access the extra custom data
- Using new chunks is technically supported but doesn't seem to have much use (padding with 0x00 bytes to hit alignment requirements is probably fine)
-----

Ed Mackey [10:30 AM]
@deadpin Rather than do that, I think a more standard approach would be to store the custom data in its own `bufferView` view into the single GLB binary chunk.  A glTF extension could be used to specify the index of which bufferView holds the custom data.

Don McCurdy [11:22 AM]
@deadpin @VPenades @Ed Mackey I agree with Ed that using a `bufferView` would be the more standard approach. That said, I believe it _is_ valid to append custom chunks after the default two. From https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#chunks –

> Client implementations must ignore chunks with unknown types to enable glTF extensions to reference additional chunks with new types following the first two chunks.
(edited)

In either case, an extension should be included to identify the model as non-standard.

**Comment by jessey-git** [comment]
iostream support has now been checked in to master.
