### ISSUE TITLE
Warnings with clang

### ISSUE THREAD

**Issue by enci** [jessey-git/fx-gltf#66]
When compiling with clang I am getting the following warnings:
```
-Wc++11-narrowing
-Wtautological-constant-out-of-range-compare
```
Namely it doesn't like the DecodeMap array of chars to be initialized with int literals. At current I am suppressing the warning and I am not sure if casting all the numbers to chars will make the code would be an "improvement".

**Comment by jessey-git** [comment]
Hi enci, I tried to repro this locally here and I can't seem to get clang to generate warnings for the code (tried versions 7 and 8, and with an online compiler for 9 and 10).  What is the full set of args you are passing as maybe I'm missing something else.

I may have a fix either way but would like to confirm directly against clang before committing if possible

**Comment by enci** [comment]
It looks like the version of clang that I am using is significantly different from mainline Clang and it has it's own version numbering.

I'll upgrade to latest that I can (fx-gltf and clang) and see if I still see the warning. Either way, this issue can be closed.

**Comment by jessey-git** [comment]
Closing for now. Can open a new issue once a good repro is found.

**Comment by TheJackiMonster** [comment]
I would like to reopen the issue. I get similar warnings which get handled as errors and break my build process using GCC 10.2.1 on a Raspberry Pi 4 (with Raspian):
```
fx-gltf/include/fx/gltf.h:86:9: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ [-Wnarrowing]
```

It might be possible to workaround it by disabling warnings or treating them not as errors but since compilers on different systems will use a different set of flags to be configured as default. It would really help if the code would actually solve it. I assume explicitly casting the values should do good.
